name: newlife_app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  dio: ^5.7.0
  url_launcher: ^6.1.10
  image_picker: ^1.1.2
  path_provider: ^2.0.10
  sqflite: ^2.4.0
  path: ^1.9.0
  smooth_page_indicator: ^1.2.0+3
  get_storage: ^2.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - "images/"
    - "images/dogs/"
    - "images/cats/"
