name: newlife_app
description: "A new Flutter project."
# publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  dio: ^5.7.0
  url_launcher: ^6.1.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  image_picker: ^1.1.2
  

flutter:
  uses-material-design: true
  assets: 
  - 'images/'
  - 'images/dogs/'
  - 'images/cats/'
 
